### ISSUE TITLE
Unable to use push_pkg function

### ISSUE THREAD

**Issue by rtirak** [adgayle/cauimws#1]
Are you able to put up an example of how to use the push_pkg function in a python script? I see you have others in your repo and I have been trying to work with the CAUIMWS library particularly the push_pkg function but with now luck. If you were able to upload or post an example on how to use this it would be very helpful. Thanks for the work and effort you have put in on what you have up currently is has been a big help.

Thanks!

**Comment by adgayle** [comment]
There is an example posted here https://github.com/adgayle/cauimws/blob/master/push-pkg-by-robot.py#L70.

**Comment by adgayle** [comment]
Example posted. Closing issue.
